#!/bin/sh

$comm -f tests/dimin.train -t tests/dimin.test -a2 

$comm -f tests/dimin.train -t tests/dimin.test -a2 -q0

$comm -f tests/dimin.train -t tests/dimin.test -q0 

$comm -f tests/dimin.train -t tests/dimin.test -a2 -q1


