#!/bin/sh
#
# defaults:
#

echo Testing Servers
exec="$VG $timbl_bin/timblserver"
client="$VG $timbl_bin/timblclient"

if test x"${VG}" = x; then
  doD="--daemonize=yes"
else
  doD="--daemonize=no"
fi

if test ! -d /tmp/run/ ; then
  mkdir /tmp/run/
fi
rm -rf /tmp/server*.log
rm -rf /tmp/run/pid*

$exec $doD --config=./tests/jsonserver.cfg --logfile=/tmp/server8.log --pidfile=/tmp/run/pid8 &
sleep 5

./jsonclient1 > tests/jsonclient1.out &
./jsonclient2 > tests/jsonclient2.out &
./jsonclient3 > tests/jsonslinet3.out &

sleep 5
kill `cat /tmp/run/pid8`

cat jsonin.1.log
cat jsonin.2.log
cat jsonin.3.log
sort /tmp/server8.log
