#!/usr/bin/expect -f
#
set timeout 5
spawn telnet localhost 7360
expect "Trying 127.0.0.1..."
expect "Connected to localhost."
expect "Escape character is '^]'."
expect -exact "Welcome to the Timbl server.\r"
expect -re "available.*3\n" # the bases line
log_file -noappend jsonin.4.log
send { {"command":"base","param":"dimin1"} }
send "\n"
expect -re ".*\n" # the send json
send { {"command":"classify","param":"=,=,=,=,=,=,=,=,+,br,L,t,J"} }
send "\n"
expect -re ".*\n" # the send json
expect -re ".*\n" # the received json
send { {"command":"set","param":"-vdi -vdb -vn"} }
send "\n"
expect -re ".*\n" # the send json
expect -re ".*ok.*\n" # the received json
send { {"command":"classify","param":"=,=,=,=,=,=,=,=,+,br,L,t,J"} }
send "\n"
expect -re ".*\n" # the send json
expect -re ".*\n" # the received json
log_file
