#!/bin/bash
#
# defaults:
#

echo Testing Servers
exec="$VG $timbl_bin/timblserver"
client="$VG $timbl_bin/timblclient"

lh=`hostname`
if test "$lh" = "kokos"
then
  lh="localhost"
fi

if test x"${VG}" = x; then
  doD="--daemonize=yes"
else
  doD="--daemonize=no"
fi

if test ! -d /tmp/run/ ; then
  mkdir /tmp/run/
fi
rm -rf /tmp/server*.log
rm -rf /tmp/run/pid*

$exec $doD -f ./tests/dimin.train -S 17345 --logfile=/tmp/server1.log --pidfile=/tmp/run/pid1&
sleep 10

\rm -f /tmp/dimin.out
$client -n $lh -p 17345 < ./tests/dimin.test.scr > /tmp/dimin.out
cat /tmp/dimin.out
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-1.out --batch
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-2.out --batch
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-3.out --batch
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-4.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-5.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-6.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-7.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-8.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-9.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-10.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-11.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-12.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-13.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-14.out --batch &
    sleep 1
$client -n $lh -p 17345  -i ./tests/dimin.test -o /tmp/dimin2-15.out --batch &
   sleep 1
sleep 10
cat /tmp/dimin2-5.out
kill `cat /tmp/run/pid1`
cat /tmp/server1.log

rm -rf /tmp/server2.log
$exec $doD -f ./tests/dimin.train -a1 +D -S 17346 --logfile=/tmp/server2.log --pidfile=/tmp/run/pid2 &
sleep 5

\rm -f /tmp/dimin.out
$client -n $lh -p 17346 < ./tests/dimin.test.scr > /tmp/dimin.out
cat /tmp/dimin.out
$client -n $lh -p 17346  -i ./tests/dimin.test -o /tmp/dimin2.out --batch
sleep 10
cat /tmp/dimin2.out
kill `cat /tmp/run/pid2`
cat /tmp/server2.log

rm -rf /tmp/server3.log
$exec $doD --config=./tests/tcpserver.cfg +vCD --logfile=/tmp/server3.log --pidfile=/tmp/run/pid3 &
sleep 10

\rm -f /tmp/dimin.out
$client -n $lh -p 17000 < ./tests/dimin.test.scr > /tmp/dimin.out
cat /tmp/dimin.out
$client -n $lh -p 17000  -i ./tests/dimin.test -o /tmp/dimin0.out --batch -b dimin0 &
$client -n $lh -p 17000  -i ./tests/dimin.test -o /tmp/dimin2.out --batch -b dimin2 &
sleep 10
cat /tmp/dimin0.out
cat /tmp/dimin2.out
kill `cat /tmp/run/pid3`
cat /tmp/server3.log

rm -rf /tmp/server4.log
$exec $doD -f ./tests/dimin.train -mO:I1 -S 17347 --logfile=/tmp/server4.log --pidfile=/tmp/run/pid4&
sleep 5

\rm -f /tmp/dimin4.out
$client -n $lh -p 17347 < ./tests/dimin.test.scr > /tmp/dimin4.out
cat /tmp/dimin4.out
kill `cat /tmp/run/pid4`
cat /tmp/server4.log

rm -rf /tmp/server5.log
$exec $doD -f ./tests/dimin.train -mM:I3 --matrixin=./tests/dimin.mat -S 17348 --logfile=/tmp/server5.log --pidfile=/tmp/run/pid5&
sleep 5

\rm -f /tmp/dimin5.out
$client -n $lh -p 17348 < ./tests/dimin.test.scr > /tmp/dimin5.out
cat /tmp/dimin5.out
kill `cat /tmp/run/pid5`
cat /tmp/server5.log

\rm -f /tmp/dimin6-*.out
$exec $doD -f ./tests/dimin.train -S 17349 --logfile=/tmp/server6.log --pidfile=/tmp/run/pid6&
sleep 10

$client -n $lh -p 17349 < ./tests/dimin.test.scr1 > /tmp/dimin6-1.out &
$client -n $lh -p 17349 < ./tests/dimin.test.scr2 > /tmp/dimin6-2.out &
$client -n $lh -p 17349 < ./tests/dimin.test.scr3 > /tmp/dimin6-3.out &
sleep 4
cat /tmp/dimin6-1.out
cat /tmp/dimin6-2.out
cat /tmp/dimin6-3.out
kill `cat /tmp/run/pid6`
cat /tmp/server6.log

\rm -f /tmp/dimin6-*.out
$exec $doD -f ./tests/dimin.train -S 17350 --logfile=/tmp/server7.log --pidfile=/tmp/run/pid7 +vdi+cf -G &
sleep 10

$client -n $lh -p 17350 < ./tests/dimin.test.scr1 > /tmp/dimin7-1.out &
$client -n $lh -p 17350 < ./tests/dimin.test.scr2 > /tmp/dimin7-2.out &
$client -n $lh -p 17350 < ./tests/dimin.test.scr3 > /tmp/dimin7-3.out &
sleep 4
cat /tmp/dimin7-1.out
cat /tmp/dimin7-2.out
cat /tmp/dimin7-3.out
kill `cat /tmp/run/pid7`
cat /tmp/server7.log
