#!/bin/sh
#
# defaults:
#

$comm -f ./tests/hapax.train -t ./tests/hapax.test.small +vdi+db -e10 -mL -o test.out1
cat < test.out1

$comm -f ./tests/hapax.train -t ./tests/hapax.test.small +vdi+db -e10 -mL -o test.out2 --limit=8
cat < test.out2
